//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuruKuruClicker.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KuruKuruClicker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {
        ///    &quot;contributors&quot;: [
        ///        {
        ///            &quot;username&quot;: &quot;xXKoksMenXx&quot;,
        ///            &quot;thing&quot;: &quot;Main Dev&quot;,
        ///            &quot;socialmedia&quot;: {
        ///                &quot;github&quot;: &quot;KoksMen&quot;
        ///            },
        ///            &quot;icon&quot;: &quot;https://avatars.githubusercontent.com/u/105588059?v=4&quot;
        ///        },
        ///        {
        ///            &quot;username&quot;: &quot;vgwik&quot;,
        ///            &quot;thing&quot;: &quot;Main Translator&quot;,
        ///            &quot;socialmedia&quot;: {
        ///              &quot;github&quot;: &quot;vgwik&quot;
        ///            },
        ///            &quot;icon&quot;: &quot;https://avatars.githubusercontent.com/u/522 [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string credits_pc {
            get {
                return ResourceManager.GetString("credits_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {
        ///    &quot;contributors&quot;: [
        ///        {
        ///            &quot;username&quot;: &quot;duiqt&quot;,
        ///            &quot;name&quot;: &quot;Phúc Duy&quot;,
        ///            &quot;thing&quot;: &quot;Main Dev&quot;,
        ///            &quot;socialmedia&quot;: {
        ///                &quot;github&quot;: &quot;duiqt&quot;
        ///            },
        ///            &quot;icon&quot;: &quot;https://avatars.githubusercontent.com/u/90624125?v=4&quot;
        ///        },
        ///        {
        ///            &quot;username&quot;: &quot;risbi0&quot;,
        ///            &quot;thing&quot;: &quot;Main Dev&quot;,
        ///            &quot;socialmedia&quot;: {
        ///                &quot;github&quot;: &quot;risbi0&quot;
        ///            },
        ///            &quot;icon&quot;: &quot;https://avatars.github [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string credits_web {
            get {
                return ResourceManager.GetString("credits_web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream kuru1 {
            get {
                return ResourceManager.GetStream("kuru1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream kuru2 {
            get {
                return ResourceManager.GetStream("kuru2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream kuruto {
            get {
                return ResourceManager.GetStream("kuruto", resourceCulture);
            }
        }
    }
}
